[custom.all.qutescript]
type   = "local"
path   = "."
ipkg   = "qutescript.ipkg"

[custom.all.qutescript-debug]
type   = "local"
path   = "examples/debug"
ipkg   = "qutescript-debug.ipkg"

[custom.all.qutescript-github]
type   = "local"
path   = "examples/github"
ipkg   = "qutescript-github.ipkg"
